name: PR Validation

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Basic checks
        run: |
          echo "Run lint/tests here"
          echo "No deployment in PR stage"
